import "./globals.css";

export const metadata = {
  title: "CraftKit | Frontend",
  description: "Next.js starter generated by CraftKit"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}