import type { Metadata } from "next";

import "./globals.css";

export const metadata: Metadata = {
  title: "CraftKit | Frontend",
  description: "Next.js starter generated by CraftKit"
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}